USE `middenbeemster_Smidse`;

INSERT INTO Content (Location, ApiName, Content, Type, PublishedBy) VALUES
('ExperienceSection', '1', 'ONTDEK &amp; BELEVEN', 'text', 'admin'),
('ExperienceSection', '2', 'Twee manieren om geschiedenis te ervaren', 'text', 'admin'),
('ExperienceSection', '3', 'Leer meer over de rijke historie van Midden-Beemster of stap direct de virtuele wereld in via onze interactieve 3D scan.', 'text', 'admin'),
('ExperienceSection', '4', '?', 'image', 'admin'),
('ExperienceSection', '5', 'Midden-Beemster', 'text', 'admin'),
('ExperienceSection', '6', '?', 'image', 'admin'),
('ExperienceSection', '7', '3D INTERACTIEF', 'text', 'admin'),
('ExperienceSection', '8', '3D Scan Ervaring', 'text', 'admin'),
('ExperienceSection', '9', 'Loop door historische gebouwen van Midden-Beemster, klik op objecten en reis terug in de tijd.', 'text', 'admin'),
('ExperienceSection', '10', '360° Rondlopen', 'text', 'admin'),
('ExperienceSection', '11', 'Tijdreizen', 'text', 'admin'),
('ExperienceSection', '12', 'Interacties', 'text', 'admin'),
('ExperienceSection', '13', 'Midden-Beemster is een pittoresk dorp in de Beemsterpolder — één van de oudste droogmakerijen ter wereld. Drooggelegd in 1612 en in 1999 aangewezen als UNESCO Werelderfgoed, staat de Beemster bekend om zijn unieke rechthoekige landschapspatroon en rijke landbouwgeschiedenis.', 'text', 'admin'),
('ExperienceSection', '14', 'OVER DE 3D ERVARING', 'text', 'admin'),
('ExperienceSection', '15', '70%', 'text', 'admin'),
('ExperienceSection', '16', 'Dankzij geavanceerde 3D-scanningtechnologie is Midden-Beemster volledig digitaal vastgelegd. Loop door historische gebouwen, bekijk details van eeuwenoude architectuur en ontdek verhalen die verborgen zijn in de muren.', 'text', 'admin'),
('ExperienceSection', '17', '360° rondlopen', 'text', 'admin'),
('ExperienceSection', '18', 'Object interacties', 'text', 'admin'),
('ExperienceSection', '19', 'Meerdere locaties', 'text', 'admin'),
('ExperienceSection', '20', 'Tijdreizen', 'text', 'admin'),
('ExperienceSection', '21', 'Unieke digitale erfgoed ervaring', 'text', 'admin'),
('ExperienceSection', '22', '▶ Start de 3D Tour', 'text', 'admin'),
('ExperienceSection', '23', '3D SCAN ERVARING', 'image', 'admin'),
('ExperienceSection', '24', 'LIVE', 'text', 'admin'),
('ExperienceSection', '25', 'Betreedt Midden-Beemster', 'text', 'admin'),
('ExperienceSection', '26', 'Volledig interactieve 3D scan omgeving', 'text', 'admin'),
('ExperienceSection', '27', '360°', 'text', 'admin'),
('ExperienceSection', '28', 'Rondlopen', 'text', 'admin'),
('ExperienceSection', '29', '4K', 'text', 'admin'),
('ExperienceSection', '30', 'Kwaliteit', 'text', 'admin'),
('ExperienceSection', '31', '1612', 'text', 'admin'),
('ExperienceSection', '32', 'Tijdperk', 'text', 'admin'),
('ExperienceSection', '33', 'Stap in een levensechte digitale reconstructie van Midden-Beemster. Verken gebouwen van binnenuit, klik op historische objecten voor verborgen verhalen en maak een reis door de tijd.', 'text', 'admin'),
('ExperienceSection', '34', 'Vrij rondlopen', 'text', 'admin'),
('ExperienceSection', '35', 'Navigeer door elk gebouw en elke straat', 'text', 'admin'),
('ExperienceSection', '36', 'Object interacties', 'text', 'admin'),
('ExperienceSection', '37', 'Klik op historische objecten voor informatie', 'text', 'admin'),
('ExperienceSection', '38', 'Meerdere tijdperken', 'text', 'admin'),
('ExperienceSection', '39', 'Zie hoe Beemster veranderde door de eeuwen', 'text', 'admin'),
('ExperienceSection', '40', '▶ Start 3D Wandeling', 'text', 'admin'),
('ExperienceSection', '41', '?', 'image', 'admin'),
('ExperienceSection', '42', '?', 'image', 'admin'),
('ExperienceSection', '43', '?', 'image', 'admin'),
('FooterSection', '1', 'Midden-Beemster', 'text', 'admin'),
('FooterSection', '2', 'Digitaal Erfgoed Project', 'text', 'admin'),
('FooterSection', '3', 'UNESCO Werelderfgoed · Beemster Polder, Noord-Holland', 'text', 'admin'),
('FooterSection', '4', '© 2024 Midden-Beemster 3D Scan Project. Alle rechten voorbehouden.', 'text', 'admin'),
('FooterSection', '5', 'Over ons', 'text', 'admin'),
('FooterSection', '6', 'Contact', 'text', 'admin'),
('FooterSection', '7', 'Privacy', 'text', 'admin'),
('HeroSection', '1', 'BEGIN DE ERVARING', 'text', 'admin'),
('HeroSection', '2', 'Begin de', 'text', 'admin'),
('HeroSection', '3', '3D Ervaring', 'text', 'admin'),
('HeroSection', '4', 'Stap direct in de interactieve 3D scan van Midden-Beemster. Geen download vereist — speel direct in je browser.', 'text', 'admin'),
('HeroSection', '5', '360° Rondlopen', 'text', 'admin'),
('HeroSection', '6', 'Tijdreizen', 'text', 'admin'),
('HeroSection', '7', 'Object interacties', 'text', 'admin'),
('HeroSection', '8', 'Gratis toegang', 'text', 'admin'),
('HeroSection', '9', 'Meer Ontdekken ↓', 'text', 'admin'),
('HeroSection', '10', 'Klik om te starten', 'text', 'admin'),
('HeroSection', '11', '?', 'image', 'admin'),
('NavBar', '1', 'Midden-Beemster', 'text', 'admin'),
('NavBar', '2', 'Ontdekken', 'text', 'admin'),
('NavBar', '3', '3D Tour', 'text', 'admin'),
('NavBar', '4', 'Speel Nu →', 'text', 'admin');